title: christerbeke.com
description: Bio and Portfolio of Chris ter Beke
permalink: pretty

excerpt_separator: <!--more-->
markdown: kramdown
highlighter: rouge

include: ['_pages']

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

github:
  repository_url: https://github.com/ChrisTerBeke/christerbeke.github.io
